# Generated by Django 5.2.5 on 2025-09-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_ownew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='ownew',
            new_name='owner',
        ),
    ]
